const surnames = [
    'Rose',
    'Wen',
    'Shadrick',
    'Summitt',
    'Sloat',
    'Nero',
    'Schwarz',
    'Gagner',
    'Facemire',
    'Hwang',
    'Hume',
    'Steckler',
    'Allan',
    'Barringer',
    'Pecora',
    'Inouye',
    'Baumann',
    'Helmer',
    'Restrepo',
    'Cimmino',
    'Beadle',
    'Rivero',
    'Collie',
    'Wamsley',
    'Alexandria',
    'Layne',
    'Kang',
    'Kuehner',
    'Eakins',
    'Mcgonagle',
    'Perrella',
    'Andrea',
    'Reda',
    'Trotman',
    'Dalke',
    'Devens',
    'Persaud',
    'Higbee',
    'Benesh',
    'Manrique',
]

const names = [
    'Rob',
    'Willy',
    'Amos',
    'Alfredo',
    'Edgardo',
    'Lupe',
    'Dale',
    'Noe',
    'Dorsey',
    'Gilberto',
    'Weston',
    'Gaston',
    'Kelvin',
    'Gene',
    'Stacey',
    'Roderick',
    'Jermaine',
    'Lucio',
    'Warren',
    'Alan',
    'Altha',
    'Marivel',
    'Terrie',
    'Otelia',
    'Milagro',
    'Dodie',
    'Kathy',
    'Zoila',
    'Aleen',
    'Concetta',
    'Basilia',
    'Faustina',
    'Charlsie',
    'Marquita',
    'Xiomara',
    'Lieselotte',
    'Thalia',
    'Sheryl',
    'Lin',
    'Faviola',
]

const cities = [
    'Vleport',
    'Nomton',
    'Blodvine',
    'Cluport',
    'Wruulchester',
    'Vlurg',
    'Fralo',
    'Phurgh',
    'Okginia',
    'Ensphis',
    'Lyri',
    'Excelle',
    'Arca',
    'Ornamentis',
    'Peom',
    'Arcadia',
    'Grace',
    'Poetry',
    'Hallow',
    'Grandeur',
    'Mageburn',
    'Landwald',
    'Marbletown',
    'Marshpond',
    'Summerlake',
    'Wyvernedge',
    'Lochwald',
    'Ironmerrow',
    'Oakbank',
    'Drackeep',
    'Foghaven',
    'Snowcoast',
    'Oldwood',
    'Bluebridge',
    'Springwood',
]

const askPhrases = [
    'Poderia me dar uma carona até',
]

const askPhrasesSon = [
    'Poderia nos dar uma carona até',
]

const askPhrasesSons = [
    'Poderia nos dar uma carona até',
]

const radioPhrases = [
    {day: 1, text: 'Por enquanto não temos muitas novidades, mas quando tivemos estaremos passando pra vocês'},
    {day: 1, text: 'Pedimos que todos guardem comida e agua e fiquem em suas casas'},
    {day: 1, text: 'Isso é algo passageiro, vai passar logo'},
    {day: 1, text: 'Arrependam-se enquanto ainda hà tempo, os juízos de Deus estão sobre nós'},
    {day: 1, text: ''},
    {day: 1, text: ''},
    {day: 1, text: ''},
    {day: 1, text: ''},
    {day: 1, text: ''},
    {day: 1, text: ''},
    {day: 1, text: ''},
    {day: 1, text: ''},
    {day: 2, text: ''},
]

const carPhrases = [
    
]

const timeOfChoices = [5, 15, 30, 45, 60, 120, 300]

const colorsOfSky = [
    ['#00000c'],
    ['#020111', '#191621'],
    ['#020111', '#20202c'],
    ['#020111', '#3a3a52'],
    ['#20202c', '#515175'],
    ['#40405c', '#6f71aa', '#8a76ab'],
    ['#4a4969', '#7072ab', '#cd82a0'],
    ['#757abf', '#8583be', '#eab0d1'],
    ['#82addb', '#ebb2b1'],
    ['#94c5f8', '#a6e6ff', '#b1b5ea'],
    ['#b7eaff', '#94dfff'],
    ['#9be2fe', '#67d1fb'],
    ['#90dffe', '#38a3d1'],
    ['#57c1eb', '#246fa8'],
    ['#2d91c2', '#1e528e'],
    ['#2473ab', '#1e528e', '#5b7983'],
    ['#1e528e', '#265889', '#9da671'],
    ['#1e528e', '#728a7c', '#e9ce5d'],
    ['#154277', '#576e71', '#e1c45e ', '#b26339'],
    ['#163C52', '#4F4F47', '#C5752D ', '#B7490F ', ' #2F1107'],
    ['#071B26', '#071B26', '#8A3B12 ', '#240E03'],
    ['#010A10', '#59230B', '#2F1107'],
    ['#090401', '#4B1D06'],
    ['#00000c', '#150800'],
    ['#00000c'],
]

/**
 * DIA 1
 * 22/03/1964
 */