const surnames = [
    'Rose',
    'Wen',
    'Shadrick',
    'Summitt',
    'Sloat',
    'Nero',
    'Schwarz',
    'Gagner',
    'Facemire',
    'Hwang',
    'Hume',
    'Steckler',
    'Allan',
    'Barringer',
    'Pecora',
    'Inouye',
    'Baumann',
    'Helmer',
    'Restrepo',
    'Cimmino',
    'Beadle',
    'Rivero',
    'Collie',
    'Wamsley',
    'Alexandria',
    'Layne',
    'Kang',
    'Kuehner',
    'Eakins',
    'Mcgonagle',
    'Perrella',
    'Andrea',
    'Reda',
    'Trotman',
    'Dalke',
    'Devens',
    'Persaud',
    'Higbee',
    'Benesh',
    'Manrique',
]

const names = [
    'Rob',
    'Willy',
    'Amos',
    'Alfredo',
    'Edgardo',
    'Lupe',
    'Dale',
    'Noe',
    'Dorsey',
    'Gilberto',
    'Weston',
    'Gaston',
    'Kelvin',
    'Gene',
    'Stacey',
    'Roderick',
    'Jermaine',
    'Lucio',
    'Warren',
    'Alan',
    'Altha',
    'Marivel',
    'Terrie',
    'Otelia',
    'Milagro',
    'Dodie',
    'Kathy',
    'Zoila',
    'Aleen',
    'Concetta',
    'Basilia',
    'Faustina',
    'Charlsie',
    'Marquita',
    'Xiomara',
    'Lieselotte',
    'Thalia',
    'Sheryl',
    'Lin',
    'Faviola',
]

const cities = [
    'Vleport',
    'Nomton',
    'Blodvine',
    'Cluport',
    'Wruulchester',
    'Vlurg',
    'Fralo',
    'Phurgh',
    'Okginia',
    'Ensphis',
    'Lyri',
    'Excelle',
    'Arca',
    'Ornamentis',
    'Peom',
    'Arcadia',
    'Grace',
    'Poetry',
    'Hallow',
    'Grandeur',
    'Mageburn',
    'Landwald',
    'Marbletown',
    'Marshpond',
    'Summerlake',
    'Wyvernedge',
    'Lochwald',
    'Ironmerrow',
    'Oakbank',
    'Drackeep',
    'Foghaven',
    'Snowcoast',
    'Oldwood',
    'Bluebridge',
    'Springwood',
]

const askPhrases = [
    'Poderia me dar uma carona até',
]

const askPhrasesSon = [
    'Poderia nos dar uma carona até',
]

const askPhrasesSons = [
    'Poderia nos dar uma carona até',
]

const radioPhrases = [

]

const carPhrases = [
    
]

const timeOfChoices = [5, 15, 30, 45, 60, 120, 300]